# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.1.0"

  on_arm do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.0/Nebo-0.1.0-arm64.dmg"
    sha256 "76ead7dfa8c4223ea8899807acaa27e46090fd2bccafa6dc365f3f0894b29e1f"
  end

  on_intel do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.0/Nebo-0.1.0-amd64.dmg"
    sha256 "4644b0e3d0f0b75d68466951ee00922187dedafc6e5332f8402ebb462b67adc4"
  end

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://neboloop.com"

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/Nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
