# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.1.12"

  on_arm do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.12/Nebo-0.1.12-arm64.dmg"
    sha256 "7ac9a97627fd1ca1327a89a5c8b24f0c5956419928677439bf47c0ef2de14d0f"
  end

  on_intel do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.12/Nebo-0.1.12-amd64.dmg"
    sha256 "2b2c15b7108eb230dc500ec843df25c9c3a12c1793e87d798f6599baa6527ea4"
  end

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://github.com/NeboLoop/nebo"

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
