# Auto-generated by CI — do not edit manually
cask "nebo" do
  version "0.1.0"

  on_arm do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.0/Nebo-0.1.0-arm64.dmg"
    sha256 "3a71d60cb6affdb63261b4c7979da9ba5f855ece51b36d5da2ee4251873c0fbb"
  end

  on_intel do
    url "https://github.com/NeboLoop/nebo/releases/download/v0.1.0/Nebo-0.1.0-amd64.dmg"
    sha256 "9635ba8f8ac95162d0a2d2460482961796320b106082ebda78a0e515345d1eb8"
  end

  name "Nebo"
  desc "AI agent with web UI - your personal AI companion"
  homepage "https://neboloop.com"

  app "Nebo.app"

  binary "#{appdir}/Nebo.app/Contents/MacOS/Nebo"

  zap trash: [
    "~/Library/Application Support/Nebo",
  ]
end
